version: '3'

vars:
  IMG_DIRS:
    sh: find . -maxdepth 1 -type d -name 'img-*' | sort

tasks:
  default:
    cmds:
      - task: build
      - task: push

  build:
    cmds:
      - for: { var: IMG_DIRS }
        cmd: task -d {{.ITEM}} build

  push:
    cmds:
      - for: { var: IMG_DIRS }
        cmd: task -d {{.ITEM}} push
