version: '3'

env:
  VENDOR_NAME: weltraumschaf
  IMAGE_NAME: debian-nodejs
  IMAGE_VERSION: 3.0.0
  NO_CACHE: false

tasks:
  default:
    cmds:
      - task: build
      - task: push

  build:
    cmds: 
      - >
        docker image build
        --no-cache={{.NO_CACHE}}
        --build-arg BUILD_DATE="{{.BUILD_DATE}}"
        --build-arg BUILD_VERSION="{{.IMAGE_VERSION}}"
        --build-arg VCS_REF="{{.VCS_REF}}"
        -t {{.VENDOR_NAME}}/{{.IMAGE_NAME}}:{{.IMAGE_VERSION}} .
    vars:
      VCS_REF:
        sh: git rev-parse --short HEAD
      BUILD_DATE:
        sh: date -u +'%Y-%m-%dT%H:%M:%SZ'

  push:
    cmds:
      - docker push {{.VENDOR_NAME}}/{{.IMAGE_NAME}}:{{.IMAGE_VERSION}}
